{
 "title": "Cool Beans Cloudwatch Metrics Visualisation",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Extract & Transform  Function Invocation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "dimensions": {
      "FunctionName": "cool-beans-extract-transform-function"
     },
     "logGroups": [
      {
       "arn": "/aws/lambda/cool-beans-ETL-function",
       "name": "/aws/lambda/cool-beans-ETL-function"
      }
     ],
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/Lambda", "type": "string" }, "type": "property" },
      "select": {
       "name": "MAX",
       "parameters": [
        { "name": "Invocations", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT MAX(Invocations) FROM \"AWS/Lambda\"",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Load Function Invocation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dimensions": { "FunctionName": "cool-beans-load-function" },
     "logGroups": [
      {
       "arn": "/aws/lambda/cool-beans-ETL-function",
       "name": "/aws/lambda/cool-beans-ETL-function"
      }
     ],
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/Lambda", "type": "string" }, "type": "property" },
      "select": {
       "name": "MAX",
       "parameters": [
        { "name": "Invocations", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT MAX(Invocations) FROM \"AWS/Lambda\"",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Duration of Lambda Invocation - cool-beans-extract-transform-function",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": {
      "FunctionName": "cool-beans-extract-transform-function"
     },
     "logGroups": [
      {
       "arn": "/aws/lambda/cool-beans-ETL-function",
       "name": "/aws/lambda/cool-beans-ETL-function"
      }
     ],
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/Lambda", "type": "string" }, "type": "property" },
      "select": {
       "name": "MAX",
       "parameters": [
        { "name": "Invocations", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT MAX(Invocations) FROM \"AWS/Lambda\"",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Duration of Lambda Invocation - cool-beans-load-function",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "FunctionName": "cool-beans-load-function" },
     "logGroups": [
      {
       "arn": "/aws/lambda/cool-beans-ETL-function",
       "name": "/aws/lambda/cool-beans-ETL-function"
      }
     ],
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/Lambda", "type": "string" }, "type": "property" },
      "select": {
       "name": "MAX",
       "parameters": [
        { "name": "Invocations", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT MAX(Invocations) FROM \"AWS/Lambda\"",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Extract & Transform Function - Total Concurrent Executions In 24h",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": {
      "FunctionName": "cool-beans-extract-transform-function"
     },
     "logGroups": [
      {
       "arn": "/aws/lambda/cool-beans-ETL-function",
       "name": "/aws/lambda/cool-beans-ETL-function"
      }
     ],
     "metricName": "ConcurrentExecutions",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/Lambda", "type": "string" }, "type": "property" },
      "select": {
       "name": "MAX",
       "parameters": [
        { "name": "Invocations", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT MAX(Invocations) FROM \"AWS/Lambda\"",
     "statistic": "SampleCount"
    }
   ]
  },
  {
   "title": "Load Function - Total Concurrent Executions In 24h",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "FunctionName": "cool-beans-load-function" },
     "logGroups": [
      {
       "arn": "/aws/lambda/cool-beans-ETL-function",
       "name": "/aws/lambda/cool-beans-ETL-function"
      }
     ],
     "metricName": "ConcurrentExecutions",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/Lambda", "type": "string" }, "type": "property" },
      "select": {
       "name": "MAX",
       "parameters": [
        { "name": "Invocations", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT MAX(Invocations) FROM \"AWS/Lambda\"",
     "statistic": "SampleCount"
    }
   ]
  },
  {
   "title": "Errors - cool-beans-extract-transform-function",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "FunctionName": "cool-beans-extract-transform-function",
      "Resource": "cool-beans-extract-transform-function"
     },
     "metricName": "Errors",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum",
     "statsGroups": [ "time_stamp" ]
    }
   ]
  },
  {
   "title": "Errors - cool-beans-load-function",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "FunctionName": "cool-beans-load-function", "Resource": "cool-beans-load-function" },
     "metricName": "Errors",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum",
     "statsGroups": [ "time_stamp" ]
    }
   ]
  },
  {
   "title": "Invocations - cool-beans-extract-transform-function",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 29 },
   "targets": [
    {
     "dimensions": {
      "FunctionName": "cool-beans-extract-transform-function"
     },
     "logGroups": [
      {
       "accountId": "015206308301",
       "arn": "arn:aws:logs:eu-west-1:015206308301:log-group:/aws/lambda/cool-beans-extract-transform-function:*",
       "name": "/aws/lambda/cool-beans-extract-transform-function"
      }
     ],
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/Lambda", "type": "string" }, "type": "property" },
      "select": {
       "name": "MAX",
       "parameters": [
        { "name": "Invocations", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "cool-beans-load-function" }, "property": { "name": "FunctionName", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT MAX(Invocations) FROM \"AWS/Lambda\" WHERE FunctionName = 'cool-beans-load-function'",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Invocations - cool-beans-load-function",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "dimensions": { "FunctionName": "cool-beans-load-function" },
     "logGroups": [
      {
       "accountId": "015206308301",
       "arn": "arn:aws:logs:eu-west-1:015206308301:log-group:/aws/lambda/cool-beans-extract-transform-function:*",
       "name": "/aws/lambda/cool-beans-extract-transform-function"
      }
     ],
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/Lambda", "type": "string" }, "type": "property" },
      "select": {
       "name": "MAX",
       "parameters": [
        { "name": "Invocations", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "cool-beans-load-function" }, "property": { "name": "FunctionName", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT MAX(Invocations) FROM \"AWS/Lambda\" WHERE FunctionName = 'cool-beans-load-function'",
     "statistic": "Sum"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } }
 ]
}