on:
  pull_request:
    types:
      - opened
      - reopened
    

permissions:
  id-token: write
  contents: read 

jobs:
  run-unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install test dependencies
        run: python3 -m pip install -r requirements-test.txt
      - name: Run unit tests
        run: python3 -m pytest -v
